name: Build and Push Base Image

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'scripts/**'
      - '.github/workflows/build-base.yml'
  workflow_dispatch:

env:
  REGISTRY: registry.cn-beijing.aliyuncs.com
  IMAGE_NAME: yoce/cuda
  IMAGE_TAG: cu121-build

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Aliyun Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.ALIYUN_USERNAME }}
        password: ${{ secrets.ALIYUN_PASSWORD }}

    - name: Build and push base image
      uses: docker/build-push-action@v5
      with:
        context: .
        target: base-builder
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64

    - name: Build and push production image
      uses: docker/build-push-action@v5
      with:
        context: .
        target: production
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}-prod
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64
